// flow-typed signature: 23fc40045bb96c6b68c552ff73fe8d67
// flow-typed version: <<STUB>>/directed-graph-map_v^1.1.0/flow_v0.60.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'directed-graph-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'directed-graph-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'directed-graph-map/dist/index' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/cross-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint-config-bunchtogether_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-flowtype_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-import_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/expect_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/flow-remove-types_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/ip_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/jest_v21.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/pre-commit_vx.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/flow-typed/npm/uuid_v3.x.x' {
  declare module.exports: any;
}

declare module 'directed-graph-map/src/index' {
  declare module.exports: any;
}

declare module 'directed-graph-map/tests/directed-graph.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'directed-graph-map/dist/index.js' {
  declare module.exports: $Exports<'directed-graph-map/dist/index'>;
}
declare module 'directed-graph-map/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/cross-env_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/cross-env_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint-config-bunchtogether_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint-config-bunchtogether_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-flowtype_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint-plugin-flowtype_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint-plugin-flowtype-errors_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-import_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint-plugin-import_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-jest_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint-plugin-jest_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint-plugin-jsx-a11y_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/expect_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/expect_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/flow-remove-types_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/flow-remove-types_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/ip_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/ip_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/jest_v21.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/jest_v21.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/pre-commit_vx.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/pre-commit_vx.x.x'>;
}
declare module 'directed-graph-map/flow-typed/npm/uuid_v3.x.x.js' {
  declare module.exports: $Exports<'directed-graph-map/flow-typed/npm/uuid_v3.x.x'>;
}
declare module 'directed-graph-map/src/index.js' {
  declare module.exports: $Exports<'directed-graph-map/src/index'>;
}
declare module 'directed-graph-map/tests/directed-graph.test.js' {
  declare module.exports: $Exports<'directed-graph-map/tests/directed-graph.test'>;
}
