// flow-typed signature: 3d5114c632f5d95a3a4a48841814c9f4
// flow-typed version: <<STUB>>/murmur-hash_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'murmur-hash'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'murmur-hash' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'murmur-hash/lib/v3/index' {
  declare module.exports: any;
}

declare module 'murmur-hash/lib/v3/murmur' {
  declare module.exports: any;
}

// Filename aliases
declare module 'murmur-hash/index' {
  declare module.exports: $Exports<'murmur-hash'>;
}
declare module 'murmur-hash/index.js' {
  declare module.exports: $Exports<'murmur-hash'>;
}
declare module 'murmur-hash/lib/v3/index.js' {
  declare module.exports: $Exports<'murmur-hash/lib/v3/index'>;
}
declare module 'murmur-hash/lib/v3/murmur.js' {
  declare module.exports: $Exports<'murmur-hash/lib/v3/murmur'>;
}
